# Generated by Django 2.2.12 on 2021-09-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.TextField(max_length=128)),
                ('kind', models.CharField(choices=[('books', 'Books'), ('movies', 'Movies'), ('both', 'both')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
