# Generated by Django 2.2.12 on 2021-09-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('books', models.ManyToManyField(blank=True, to='books.Book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
