# Generated by Django 2.2.12 on 2021-09-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('title', models.TextField(max_length=128)),
                ('year', models.TextField(max_length=4)),
                ('cover_images', models.ImageField(upload_to='movie_photos')),
                ('rating', models.IntegerField()),
                ('category', models.ManyToManyField(blank=True, related_name='movie', to='categories.Category')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
